# permissions for end users to view replicationconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicationconfig-viewer-role
rules:
- apiGroups:
  - config.scartel.dc
  resources:
  - replicationconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.scartel.dc
  resources:
  - replicationconfigs/status
  verbs:
  - get
