
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - config.scartel.dc
  resources:
  - replicationconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.scartel.dc
  resources:
  - replicationconfigs/status
  verbs:
  - get
  - patch
  - update
